Feature Kachaka
sbgisen/fleet_adapter_kachaka pull request #1
Opened 2024-02-16 09:43 UTC by h-wata

## Summary

- fix #

## Detail

## Impact

## Test

  

## Attention

2024-03-14 07:05 UTC, h-wata commented
3倍速ですが、2台のKachakaを操作して道の譲り合いができております。

https://github.com/sbgisen/fleet_adapter_for_kachaka/assets/20681658/14d59ed1-0cec-403c-815a-ee596658bb6e

2024-03-14 07:05 UTC, h-wata commented
動画2
https://github.com/sbgisen/fleet_adapter_for_kachaka/assets/20681658/7a554baf-c5da-4431-b5a5-c25db6b09ca9

2024-03-22 09:37 UTC, MikhailBertrand requested changes

2024-03-22 09:37 UTC, MikhailBertrand commented on README.md
下記が必要

https://github.com/pf-robotics/kachaka-api?tab=readme-ov-file#playground%E3%81%ABssh%E3%81%A7%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%99%E3%82%8B

2024-03-22 09:48 UTC, MikhailBertrand requested changes

2024-03-22 09:48 UTC, MikhailBertrand commented on README.md
> +git pull feature/rest_api_wrapper
不正なコマンド
```
git remote add h-wata https://github.com/h-wata/kachaka-api
git switch feature/rest_api_wrapper
```

2024-03-22 09:54 UTC, MikhailBertrand commented on README.md
> +git pull feature/rest_api_wrapper
こちらのPRよりも先に、kachaka-apiの方の`feature/rest_api_wrapper`ブランチをフォーク先のデフォルトブランチとして導入した方が良さそうです。

2024-03-22 09:55 UTC, MikhailBertrand commented on README.md
> +Please run `python/demos/url_kachaka_api.ipynb` in Jupyter Notebook.
（kachaka-apiリポジトリの方の修正要望）
せっかくSSHで入っているので、中でコマンドを走らせられるようにした方が良いと思います。

2024-03-22 10:11 UTC, MikhailBertrand commented on README.md
> +git pull feature/rest_api_wrapper
現在のkachaka-apiのフォークに置かれている差分は、kachaka-apiリポジトリに置かなくても良いかもしれません。

- [url_kachaka_api.ipynb](https://github.com/h-wata/kachaka-api/blob/bcc78cd2252908f21216116b20dd9487faa5f97e/python/demos/url_kachaka_api.ipynb?short_path=c778567)
  - こちらは、公式があくまでデモ用に用意しているブラウザ実行用のノートブックなので、これをそのまま変更する必要はありません。
  - また、**ユーザーが使う用の**jupyterノートブックをgit管理するのは、実行状態などが反映されてしまうjupyterノートブックの性質上難しく、公式の更新差分などを後で反映させるのに手間が生じたりしてしまう点も考慮に入れなければなりません。
  - ノートブック内のデモコードのコピペのようなもので構いませんので普通に実行可能なpythonスクリプトとして、Open-RMF補完用コードと一緒に別リポジトリで管理することをおすすめします。  
- [connect_openrmf_by_zenoh.py](https://github.com/h-wata/kachaka-api/blob/bcc78cd2252908f21216116b20dd9487faa5f97e/python/demos/connect_openrmf_by_zenoh.py)
  - すでに他所のsbgisenリポジトリでZenoh用のスクリプトを配置しようとされているかもしれませんが、こちらに関しても、特定別用途用の実行スクリプトなので、上記のスクリプトと併せて別リポジトリで管理するほうが望ましいです。

2024-03-22 10:13 UTC, MikhailBertrand commented on README.md
> +Please run `python/demos/url_kachaka_api.ipynb` in Jupyter Notebook.
上述した通り、ノートブック実行である必要性がないので、別の実行方法を考えた方が良いです。

2024-03-22 10:17 UTC, MikhailBertrand commented on fleet_adapter_for_kachaka/config.yaml
>    password: "some_password"
この設定ファイルの内容を見るに、この3つだけは直接記述できないので、このファイルをテンプレートファイル化して、ユーザー対話式で正式な個体ごとのconfig.yamlファイルを作るスクリプトを用意するのが望ましいかと思います。

2024-03-22 10:18 UTC, MikhailBertrand commented on fleet_adapter_for_kachaka/config.yaml
> +            [-1.432, -13.421]] # matsuzaki
このあたりも、環境によって異なる値となるので、執務室用の設定ファイルはNASで管理して、ここではテンプレート化した方が望ましいです。

2024-03-22 10:25 UTC, MikhailBertrand requested changes

2024-03-22 10:25 UTC, MikhailBertrand commented on fleet_adapter_for_kachaka/setup.py
このリポジトリはテンプレートなので、ライセンス表記やメンテナー情報はsbgisenのものに変えましょう

2024-03-22 10:25 UTC, MikhailBertrand commented on fleet_adapter_for_kachaka/setup.cfg
ROS2のPythonパッケージでは、setup.cfgがデフォルトであるため、これまでのように親ディレクトリにあるsetup.cfgファイルの設定を読んでくれません。
なので、私はコーディングルール（flake8とisortの設定）をここに追記するようにしています。
```
[flake8]
aggressive = 2
ignore = W503, ANN002, ANN003, ANN1, D104, N805
max-line-length = 119
select = E,F,W,C,N,I,D,ANN
; accept-encodings = utf-8
classmethod-decorators = classmethod,validator
copyright-check = True
copyright-regexp = # Copyright \(c\) [0-9]{4} SoftBank Corp\.\n#\n# Licensed under the Apache License, Version 2\.0 \(the "License"\);\n# you may not use this file except in compliance with the License\.\n# You may obtain a copy of the License at\n#\n#     http\:\/\/www\.apache\.org\/licenses\/LICENSE-2\.0\n#\n# Unless required by applicable law or agreed to in writing, software\n# distributed under the License is distributed on an "AS IS" BASIS,\n# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\.\n# See the License for the specific language governing permissions and\n# limitations under the License\.
docstring-convention = google
suppress-dummy-args = True
[isort]
line_length=119
force_single_line = True
```

2024-03-26 02:14 UTC, h-wata commented on README.md
> +git pull feature/rest_api_wrapper
https://github.com/sbgisen/kachaka-api-for-openrmf/pull/1
こちらでAPIをまとめました。

2024-04-01 04:23 UTC, h-wata commented on fleet_adapter_for_kachaka/config.yaml
> +            [-1.432, -13.421]] # matsuzaki
config 作成Scirptを作成しました。

2024-04-01 04:24 UTC, h-wata commented on fleet_adapter_for_kachaka/config.yaml
>    password: "some_password"
config作成スクリプトを追加しました。

2024-04-01 04:26 UTC, h-wata commented on fleet_adapter_for_kachaka/setup.cfg
setup.cfgファイルを追加しました。

2024-04-01 08:54 UTC, h-wata commented on fleet_adapter_for_kachaka/setup.py
[1b0910c](https://github.com/sbgisen/fleet_adapter_for_kachaka/pull/1/commits/1b0910c5ad57517cfd8134ed9ac79d6e66ad6f16)似て修正しました。

2024-04-03 02:51 UTC, MikhailBertrand commented
こちらにいくつかのadapterの先行実装が提示されているのですが、`fleet_adapter_hoge`という形で命名されているリポジトリが多いので、このリポジトリも`for`を省いて`fleet_adapter_kachaka`にした方が良い気がします（文字数減りますし）。

https://github.com/open-rmf/awesome_adapters

2024-04-03 05:12 UTC, MikhailBertrand requested changes

2024-04-03 05:12 UTC, KenyuKurimoto commented on fleet_adapter_for_kachaka/setup.py
> +import os  # noqa: C101
noqaなんかにせずに、普通にshebangとライセンス表記書き足して問題ないと思います。

2024-04-03 05:12 UTC, KenyuKurimoto commented on fleet_adapter_for_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
```xml
  <maintainer email="SBGRP-git@g.softbank.co.jp">SoftBank corp.</maintainer>
```

2024-04-03 05:12 UTC, MikhailBertrand commented on fleet_adapter_kachaka/setup.py
>      maintainer_email='yadunund@openrobotics.org',
未更新

2024-04-03 05:21 UTC, MikhailBertrand requested changes

2024-04-03 05:21 UTC, MikhailBertrand commented on fleet_adapter_kachaka/config1.yaml
テンプレートを作ったので実際のファイルは削除してsbgisen用NASで管理しましょう

2024-04-03 05:23 UTC, h-wata commented on fleet_adapter_kachaka/config1.yaml
template_config.yamlにRenameして、gitignoreにconfig_*.yamlを入れたほうがいいでしょうか？

2024-04-03 05:42 UTC, MikhailBertrand requested changes

2024-04-03 05:42 UTC, MikhailBertrand commented on fleet_adapter_kachaka/fleet_adapter_kachaka/RobotClientAPI.py
> +import requests
場所をライセンスの下に

2024-04-03 05:49 UTC, MikhailBertrand commented on fleet_adapter_kachaka/fleet_adapter_kachaka/RobotClientAPI.py
> +        self.requires_replan = requires_replan
`requires_replan`はテンプレにもありましたが、これなんで必要かわかりますか？
テンプレ実装例見ても使われてなさそうだったのですが…。

2024-04-03 06:11 UTC, MikhailBertrand commented on fleet_adapter_kachaka/config1.yaml
個人的にはそういった措置は必要ないんじゃないかなと思っています。

恐らくですが、すべてのfleet_adapterノードは最終的に1つのサーバー上で走らせて、configファイルもそこの中の特定ディレクトリに配置すると思います。このリポジトリである必要もないので、リポジトリ内にconfigファイルが複数配置される前提に立つ必要はないと思います。

2024-04-03 06:24 UTC, h-wata commented on fleet_adapter_kachaka/fleet_adapter_kachaka/RobotClientAPI.py
> +        self.requires_replan = requires_replan
使われてなさそうですね。。

2024-04-03 06:31 UTC, h-wata commented on fleet_adapter_kachaka/setup.py
>      maintainer_email='yadunund@openrobotics.org',
この部分ってなんでしたっけ？
`share/fleet_adapter_kachaka/launch`にあるのはおかしいって話ですかね？

2024-04-03 06:34 UTC, MikhailBertrand commented on fleet_adapter_kachaka/setup.py
>      maintainer_email='yadunund@openrobotics.org',
恐らくですが、すべてのfleet_adapterノードは

2024-04-03 06:35 UTC, MikhailBertrand commented on fleet_adapter_kachaka/fleet_adapter_kachaka/RobotClientAPI.py
> +        self.requires_replan = requires_replan
使いみちがわからないので不要な混乱を避けるためにいったんコメントアウトしてしまっても良いかもしれません。

2024-04-03 06:38 UTC, h-wata commented on fleet_adapter_kachaka/setup.py
>      maintainer_email='yadunund@openrobotics.org',
理解しました。

2024-04-03 07:45 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
これforkしてますけど上の人は元のリポジトリのメンテナーでこのフォークのメンテナンスとは関係ない人なので消した方が良いです。本当はこのテンプレートはforkするよりコピーして使う方が用途としては正しかったんじゃないかと。

2024-04-03 07:57 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
なるほど。新しくリポジトリ作ったほうが良いですか

2024-04-03 08:01 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
例えばSwitchbot介したdoor adapterは新規リポジトリとして作成しました。
https://github.com/sbgisen/door_adapter_switchbot

2024-04-03 08:04 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
なるほど。そもそもTemplateと名乗るならSettingsでTemplateにしてほしいですね。。
こちらのPRがMergeできたらリポジトリを作り直しますか。

2024-04-03 08:06 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
本家READMEにも書いてある通りただのサンプル実装なので好きなようにやればいいのですが、もうここで作り始めているので気にならないなら別に移行する必要もない気がします。

2024-04-03 08:08 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
気になっているのがForkリポジトリはDefaultだと検索に引っかからないので、できればForkはやめたいっちゃやめたいですね。

2024-04-03 08:09 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
何の検索ですか？

2024-04-03 08:11 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
![image](https://github.com/sbgisen/fleet_adapter_kachaka/assets/20681658/09c03ed8-9cf1-4a9d-9a3d-df9ca90aa92f)
Githubのリポジトリ検索です。

2024-04-03 08:14 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
人に共有したいんですか？

2024-04-03 08:15 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
参考になればいいかとは思ってます！

2024-04-03 08:17 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
あとOpen RMF実装例としてどこかで発表したくなるかもしれませんし！

2024-04-03 08:18 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
人に依るかもしれませんがテンプレートリポジトリ見た人がフォーク先見る率は高いと思うのでフォークのままでもいいかもしれませんね。正直僕はどちらでもいいですが。

2024-04-03 08:20 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
そうですか。
まぁどちらでもいいですね。あくまで現状はお試しの実装の色合いが強いですし。
REST APIでどこまで行くかわからないですしね。

2024-04-03 08:33 UTC, MikhailBertrand commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
> あくまで現状はお試しの実装の色合いが強いですし。 

そうなんですよね。

気になっちゃうのがやっぱり別にカチャカ自体はうちの会社とは何ら関係がない（特段業務提携をしているわけでもグループ会社であるわけでもない、むしろ厳密に言えばライバル会社）製品なので我々が内部で試す目的以外で堂々と社名使ってリポジトリメンテ宣言するのも変な話に聞こえます。
加えてご指摘のあった通り、まだ運用方針も決まっていない実験的実装なので、鍵リポジトリでしばらく内部実験用に使って、何かしらROS-SIアピールで活用できそうな事例、その他内製サービスのアピールに利用できそうな事例があれば発表に際して公開する、というのが適切なルートだと思います。

※ 業務時間外で渡辺さん個人が開発して個人としてROSコミュニティで発表する分には何ら問題はないと思われます

2024-04-03 08:54 UTC, h-wata commented on fleet_adapter_kachaka/package.xml
>    <maintainer email="yadunund@openrobotics.org">Yadunund</maintainer>
とりあえずmaintainerは修正しました。

2024-04-04 01:15 UTC, MikhailBertrand commented on fleet_adapter_kachaka/make_config.py
> +        f"Enter at least 4 RMF coordinates for {location_name} (enter 'q' to finish)")
僕がよく知らないのですが、この座標って最低「4つ」必要なんでしたっけ？
Open-RMFマップとロボットの体内マップ間の座標変換に必要なパラメータという認識なのですが、原理的には2つで良いように見えます。

あとレベルが増えたときの扱いが気になりますが、現在カチャカは1フロアにのみ対応しているので、そこはいったんスルーでいいですかね。

2024-04-04 01:30 UTC, h-wata commented on fleet_adapter_kachaka/make_config.py
> +        f"Enter at least 4 RMF coordinates for {location_name} (enter 'q' to finish)")
ご認識のとおりです。
ただ、おすすめは４点ということです。
https://github.com/sbgisen/fleet_adapter_kachaka/blob/6a297c0d68f962fc21d54221afbb44184e5b28ed/README.md?plain=1#L45

また、複数フロアになった場合は、Floorごとに書く必要があります。現在のスクリプトでも複数フロアに対応しています。

https://github.com/open-rmf/fleet_adapter_template/blob/6a297c0d68f962fc21d54221afbb44184e5b28ed/fleet_adapter_template/config.yaml#L56
ここにフロア名を記載するところがあるので、こちらに追加していく感じです。

2024-04-04 01:35 UTC, MikhailBertrand commented on fleet_adapter_kachaka/make_config.py
> +        f"Enter at least 4 RMF coordinates for {location_name} (enter 'q' to finish)")
> ただ、おすすめは４点ということです。

地点の数のチェックがないので入れるべきかと思いましたが入れる場合は2点でいいですか？
プロンプトで「4点推奨」と書いてあればいいので。

> ここにフロア名を記載するところがあるので、こちらに追加していく感じです。

あ、スクリプトの中で`location_name`になっていたので見逃していました。これ`level_name`に直した方が良さそうですね。

2024-04-04 01:36 UTC, KenyuKurimoto commented on fleet_adapter_kachaka/make_config.py
> +        f"Enter at least 4 RMF coordinates for {location_name} (enter 'q' to finish)")
#2 の方でついでに対応しておきます。

2024-04-04 01:43 UTC, h-wata commented on fleet_adapter_kachaka/make_config.py
> +        f"Enter at least 4 RMF coordinates for {location_name} (enter 'q' to finish)")
> 地点の数のチェックがないので入れるべきかと思いましたが入れる場合は2点でいいですか？
そうですね。よろしくおねがいします。

2024-04-04 08:35 UTC, MikhailBertrand commented
READMEにdelivery_nodeの説明が無いのですがこれは何用のスクリプトですか？

2024-04-04 08:59 UTC, h-wata commented
delivery_nodeはDelivery taskに対応するために追加したものですね。
Delivery taskを実現するためにどのTopicをPub/Subすべきかの一つの実装例となります。
README.mdに追記しますか。

2024-04-04 09:17 UTC, MikhailBertrand commented
このリポジトリに含めるのであればREADMEには必ず想定される使い方も含めて記述しましょう。
しかし、これ自体が試験用のコードというよりも、実際にOpen-RMF運用時に実行されるノードに見えるので、個人的にはここに含めるのはおすすめしません。fleet_adapterの一部ではないので。fleet_adapterの単体試験用コードであれば問題ないのですが。

2024-04-04 09:30 UTC, h-wata commented
今回は外しておきます。Deliveryタスクを実施したいときにまた検討します。そもそも現状rmf_demosに定義されているDeliveryタスクを我々が活用するかも不明ですので。

2024-04-04 09:44 UTC, MikhailBertrand approved these changes

2024-04-04 09:44 UTC, merged

2024-04-04 09:44 UTC, KenyuKurimoto commented
とりあえず、ここまでのコミットで`kachaka-api-for-openrmf`とワンセットで最低限 fleet adapter としては動くという認識なので一旦マージします。カチャカ利用に関しては最低限の準備が整ったと考えられます。

ここからフロアでの本格運用実施にあたり、あとは独自のOpen-RMF環境のセットアップ、個別設定やここからは省いたタスク実行用ノードを管理するリポジトリが必要かもしれません。

2024-04-04 10:28 UTC, h-wata commented
それはもう少しセキュアなところでやりましょうかね。

2024-04-04 10:29 UTC, MikhailBertrand commented
はい、その方が良いです。